#Numpy

# Numpy table creation

In [ ]:
import numpy as np

In [ ]:
# 1D array
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
# Linspace function (create an array in a given range with given step/ can create real values)
np.linspace(0, 50, 51)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [ ]:
# Arrange function (create an array in a given range / can only create integer numbers)
np.arange(0, 50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
# 2D array
arr_bis = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_bis

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Null matrix
o = np.zeros([3, 5])
o

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Identity matrix
I = np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Ones matrix
One = np.ones([3, 5])
One

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Add to matrix
# Two matrices must have the same shape
o + One

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Subtract two matrices 
o - One

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [ ]:
# Scalar Multiplication
I * 5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

# Random

In [ ]:
# Random 1d array in the value 0 and 1 (Ideal to simulate a ramdom weight of a wallet for example)
ran = np.random.rand(6)
ran

array([0.68714843, 0.69586839, 0.53177033, 0.30941226, 0.2230142 ,
       0.10709017])

In [ ]:
# Bonus: How to find the shape of a array and transform 1d array to 2d array
print(f"Shape is {np.shape(ran)}")

# Reshape
ran = ran.reshape(6, 1)

# New shape
print(f"Shape is {np.shape(ran)}")

Shape is (6,)
Shape is (6, 1)


In [ ]:
# Random integer value
arr_int = np.random.randint(0, 100, size = (5, 5))
arr_int

array([[40, 45, 42, 93, 64],
       [36, 44, 83, 50,  9],
       [67, 52, 63,  4, 66],
       [50, 91, 96, 83, 71],
       [ 0, 53, 63,  1, 59]])

In [ ]:
# Normal 1 dim
np.random.rand(3)

array([0.25643738, 0.73540624, 0.39592117])

In [ ]:
# Normal 2 dim
np.random.rand(3, 3)

array([[0.48637545, 0.67258914, 0.59330929],
       [0.07604654, 0.91602952, 0.22584485],
       [0.98077009, 0.64148927, 0.71858142]])

In [ ]:
# Set the seed
print(np.random.rand(3))
print(np.random.rand(3))

np.random.seed(seed = 32)
print(np.random.rand(3))

np.random.seed(seed = 32)
print(np.random.rand(3))

[0.10108656 0.92848807 0.60910917]
[0.59655344 0.09178413 0.34518624]
[0.85888927 0.37271115 0.55512878]
[0.85888927 0.37271115 0.55512878]


# Indexing Slicing Transformation

In [ ]:
# Choose one value in a matrix
arr_bis = np.array([[1, 2, 3],
                    [7, 1, 6],
                    [9, 6, 3]])

arr_bis[0][0]

1

In [ ]:
# Choose sub matrix in the matrix
arr_bis[0:2, 0:3]

array([[1, 2, 3],
       [7, 1, 6]])

In [ ]:
# Choose one columns or one row
print(arr_bis[1, :])
print(arr_bis[:, 1])

[7 1 6]
[2 1 6]


In [ ]:
# Max
# On the matrix
print(arr_bis.max())

# By the rows
print(arr_bis.max(axis = 1))

# By the columns
print(arr_bis.max(axis = 0))

9
[3 7 9]
[9 6 6]


In [ ]:
# Min
# On the matrix
print(arr_bis.min())

# By the rows
print(arr_bis.min(axis = 1))

# By the columns
print(arr_bis.min(axis = 0))

1
[1 1 3]
[1 1 3]


In [ ]:
# Mean
# On the matrix
print(arr_bis.mean())

# By the rows
print(arr_bis.mean(axis = 1))

# By the columns
print(arr_bis.mean(axis = 0))


4.222222222222222
[2.         4.66666667 6.        ]
[5.66666667 3.         4.        ]


In [ ]:
# Std
# On the matrix
print(arr_bis.std())

# By the rows
print(arr_bis.std(axis = 1))

# By the columns
print(arr_bis.std(axis = 0))


2.698879511442471
[0.81649658 2.62466929 2.44948974]
[3.39934634 2.1602469  1.41421356]


In [ ]:
# Other way available
np.max(arr_bis, axis = 1)

array([3, 7, 9])

In [ ]:
# Log function
np.log(arr_bis)

array([[0.        , 0.69314718, 1.09861229],
       [1.94591015, 0.        , 1.79175947],
       [2.19722458, 1.79175947, 1.09861229]])

In [ ]:
# Exponential function
np.exp(arr_bis)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [1.09663316e+03, 2.71828183e+00, 4.03428793e+02],
       [8.10308393e+03, 4.03428793e+02, 2.00855369e+01]])

In [ ]:
# Squared root function
np.sqrt(arr_bis)

array([[1.        , 1.41421356, 1.73205081],
       [2.64575131, 1.        , 2.44948974],
       [3.        , 2.44948974, 1.73205081]])

In [ ]:
# Concatenate
# Params: tuple of arrays and the axis of the concatenation
# Concat 1 dimension
arr1 = arr_bis[:, 1]
arr2 = arr_bis[:, 2]

print(f"ARR1 {arr1}")
print(f"ARR2 {arr2}")
print(np.concatenate((arr1, arr2), axis = 0))

ARR1 [2 1 6]
ARR2 [3 6 3]
[2 1 6 3 6 3]


In [ ]:
# Concatenate 2 dimension
arr1 = arr_bis[:, 1].reshape(-1, 1)
arr2 = arr_bis[:, 2].reshape(-1, 1)

print(f"ARR1 {arr1}")
print(f"ARR2 {arr2}")
print(np.concatenate((arr1, arr2), axis = 1))

ARR1 [[2]
 [1]
 [6]]
ARR2 [[3]
 [6]
 [3]]
[[2 3]
 [1 6]
 [6 3]]


In [ ]:
# Concatenate 2 dimension
print(np.concatenate((arr1, arr2), axis = 0))

[[2]
 [1]
 [6]
 [3]
 [6]
 [3]]


# Pandas

In [ ]:
import pandas as pd
import numpy as np

# Series and dataframes

# Series

In [ ]:
labels = ["label1", "label2", "label3"]
list_values = [1, 2, 3]
arr_values = np.array([1, 2, 3])

In [ ]:
# Create a series from a list
pd.Series(list_values, index = labels)

label1    1
label2    2
label3    3
dtype: int64

In [ ]:
# Create a series from an array
pd.Series(arr_values, index = labels)

label1    1
label2    2
label3    3
dtype: int64

# Dataframes

In [ ]:
list_columns = ["col_1", "col_2", "col_3"]
list_index = ["row_1", "row_2", "row_3"]
arr_bis = np.array([[1, 2, 3],
                    [7, 1, 6],
                    [9, 6, 3]])

In [ ]:
# Create a dataframe from an array
pd.DataFrame(arr_bis)

0  1  2
0  1  2  3
1  7  1  6
2  9  6  3

In [ ]:
# Specify rows/columns
pd.DataFrame(arr_bis, index = list_index)

0  1  2
row_1  1  2  3
row_2  7  1  6
row_3  9  6  3

# Cleaning and selection

In [ ]:
# Import of csv
assets = pd.read_csv("/content/assets.csv", parse_dates =True, index_col = "time")
assets

Open MSFT  High MSFT  Low MSFT  Close MSFT  Volume MSFT  \
time                                                                  
2020-03-18      138.0   146.0000    135.02      140.40   80794307.0   
2020-03-17      140.0   147.4998    135.00      146.57   81059817.0   
2020-03-16      140.0   149.3500    135.00      135.42   87905868.0   
2020-03-13      147.5   161.9100    140.73      158.83   92727446.0   
2020-03-12      145.3   153.4700    138.58      139.06   93226366.0   
...               ...        ...       ...         ...          ...   
2000-07-04        NaN        NaN       NaN         NaN          NaN   
2000-05-29        NaN        NaN       NaN         NaN          NaN   
2000-04-21        NaN        NaN       NaN         NaN          NaN   
2000-02-21        NaN        NaN       NaN         NaN          NaN   
2000-01-17        NaN        NaN       NaN         NaN          NaN   

            Open GOOG  High GOOG  Low GOOG  Close GOOG  Volume GOOG  ...  \
time                                                                 ...   
2020-03-18    1056.51    1106.50   1037.28     1096.80    4220935.0  ...   
2020-03-17    1093.11    1130.86   1056.01     1119.80    3861489.0  ...   
2020-03-16    1096.00    1152.27   1074.44     1084.33    4252365.0  ...   
2020-03-13    1179.00    1219.76   1117.14     1219.73    3700125.0  ...   
2020-03-12    1126.00    1193.87   1113.30     1114.91    4226748.0  ...   
...               ...        ...       ...         ...          ...  ...   
2000-07-04        NaN        NaN       NaN         NaN          NaN  ...   
2000-05-29        NaN        NaN       NaN         NaN          NaN  ...   
2000-04-21        NaN        NaN       NaN         NaN          NaN  ...   
2000-02-21        NaN        NaN       NaN         NaN          NaN  ...   
2000-01-17        NaN        NaN       NaN         NaN          NaN  ...   

            Open EUROSTOCK50  High EUROSTOCK50  Low EUROSTOCK50  \
time                                                              
2020-03-18         2507.3301         2507.3301        2365.7000   
2020-03-17         2475.1799         2555.4099        2376.2300   
2020-03-16         2557.7100         2557.7100        2302.8401   
2020-03-13         2584.3601         2793.2700        2537.2700   
2020-03-12         2883.2500         2883.2500        2535.8899   
...                      ...               ...              ...   
2000-07-04         5185.8701         5185.8701        5185.8701   
2000-05-29         5084.6899         5084.6899        5084.6899   
2000-04-21         5180.1184         5207.4892        5132.2034   
2000-02-21         5033.3301         5033.3301        5033.3301   
2000-01-17         4884.5000         4884.5000        4884.5000   

            Close EUROSTOCK50  Volume EUROSTOCK50  Open INTEL  High INTEL  \
time                                                                        
2020-03-18          2385.8201          98214900.0     30.2400     32.4550   
2020-03-17          2530.5000         106905300.0     29.0600     33.8000   
2020-03-16          2450.3701         137137000.0     30.1100     32.8450   
2020-03-13          2586.0200         136547100.0     33.8700     35.0077   
2020-03-12          2545.2300         167329900.0     35.2900     36.0432   
...                       ...                 ...         ...         ...   
2000-07-04          5185.8701                 0.0         NaN         NaN   
2000-05-29          5084.6899                 0.0         NaN         NaN   
2000-04-21          5170.3844            722995.0         NaN         NaN   
2000-02-21          5033.3301                 0.0         NaN         NaN   
2000-01-17          4884.5000                 0.0         NaN         NaN   

            Low INTEL  Close INTEL  Volume INTEL  
time                                              
2020-03-18      28.01        29.20      192337.0  
2020-03-17      28.79        32.40      273967.0  
2020-03-16      28.62

In [ ]:
# Ordonning
assets = assets.sort_index(ascending = True)

In [ ]:
# Select a column
assets = assets[["Close DJI30", "Close CAC40", "Close SP500"]]
assets

Close DJI30 Close CAC40  Close SP500
time                                            
2000-01-03   11357.5098   5917.3701    1455.2200
2000-01-04   10997.9297   5672.0200    1399.4200
2000-01-05   11122.6504   5479.7002    1402.1100
2000-01-06   11253.2598   5450.1099    1403.4500
2000-01-07   11522.5596   5539.6099    1441.4700
...                 ...         ...          ...
2020-03-15          NaN         NaN          NaN
2020-03-16   20188.5195   3881.4600    2426.6181
2020-03-17   21237.3809   3991.7800    2436.5000
2020-03-18   19898.9199   3754.8401    2398.1001
2020-03-19          NaN         NaN          NaN

[5732 rows x 3 columns]

In [ ]:
# Reset index
assets.reset_index(drop = True)

Close DJI30 Close CAC40  Close SP500
0      11357.5098   5917.3701    1455.2200
1      10997.9297   5672.0200    1399.4200
2      11122.6504   5479.7002    1402.1100
3      11253.2598   5450.1099    1403.4500
4      11522.5596   5539.6099    1441.4700
...           ...         ...          ...
5727          NaN         NaN          NaN
5728   20188.5195   3881.4600    2426.6181
5729   21237.3809   3991.7800    2436.5000
5730   19898.9199   3754.8401    2398.1001
5731          NaN         NaN          NaN

[5732 rows x 3 columns]

In [ ]:
# Missing values NaN
assets = assets.dropna()
assets

Close DJI30 Close CAC40  Close SP500
time                                            
2000-01-03   11357.5098   5917.3701    1455.2200
2000-01-04   10997.9297   5672.0200    1399.4200
2000-01-05   11122.6504   5479.7002    1402.1100
2000-01-06   11253.2598   5450.1099    1403.4500
2000-01-07   11522.5596   5539.6099    1441.4700
...                 ...         ...          ...
2020-03-12   21200.6191   4044.2600    2420.8827
2020-03-13   23185.6191   4118.3599    2418.0191
2020-03-16   20188.5195   3881.4600    2426.6181
2020-03-17   21237.3809   3991.7800    2436.5000
2020-03-18   19898.9199   3754.8401    2398.1001

[5047 rows x 3 columns]

In [ ]:
# Rolling
assets["SMA 15"] = assets[["Close SP500"]].rolling(15).mean()
assets

<ipython-input-97-c1eb2c6deea6>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  assets["SMA 15"] = assets[["Close SP500"]].rolling(15).mean()


Close DJI30 Close CAC40  Close SP500       SMA 15
time                                                         
2000-01-03   11357.5098   5917.3701    1455.2200          NaN
2000-01-04   10997.9297   5672.0200    1399.4200          NaN
2000-01-05   11122.6504   5479.7002    1402.1100          NaN
2000-01-06   11253.2598   5450.1099    1403.4500          NaN
2000-01-07   11522.5596   5539.6099    1441.4700          NaN
...                 ...         ...          ...          ...
2020-03-12   21200.6191   4044.2600    2420.8827  2445.100287
2020-03-13   23185.6191   4118.3599    2418.0191  2444.029520
2020-03-16   20188.5195   3881.4600    2426.6181  2443.003900
2020-03-17   21237.3809   3991.7800    2436.5000  2442.964567
2020-03-18   19898.9199   3754.8401    2398.1001  2440.551540

[5047 rows x 4 columns]

In [ ]:
# Shift
assets["Close SP500"].shift(1)

time
2000-01-03          NaN
2000-01-04    1455.2200
2000-01-05    1399.4200
2000-01-06    1402.1100
2000-01-07    1403.4500
                ...    
2020-03-12    2423.1280
2020-03-13    2420.8827
2020-03-16    2418.0191
2020-03-17    2426.6181
2020-03-18    2436.5000
Name: Close SP500, Length: 5047, dtype: float64

In [ ]:
# Group by mean
arr = [[1, 10],
       [1, 10],
       [3, 15]]
       
df = pd.DataFrame(arr, columns = ["num", "val"])

df.groupby(by = "num").mean()

val
num      
1    10.0
3    15.0

In [ ]:
# Groupby by sum
df.groupby(by = "num").sum()

val
num     
1     20
3     15

In [ ]:
# Groupy by std
df.groupby(by = "num").std()

val
num     
1    0.0
3    NaN

# Iloc & Loc

loc is label-based, which means that you have to specify rows and columns based on their row and column labels. iloc is integer index based, so you have to specify rows and columns by their integer index like you did in the previous exercise

In [ ]:
# Slicing
assets.iloc[0:1500, 0:10]

Close DJI30 Close CAC40  Close SP500       SMA 15
time                                                         
2000-01-03   11357.5098   5917.3701    1455.2200          NaN
2000-01-04   10997.9297   5672.0200    1399.4200          NaN
2000-01-05   11122.6504   5479.7002    1402.1100          NaN
2000-01-06   11253.2598   5450.1099    1403.4500          NaN
2000-01-07   11522.5596   5539.6099    1441.4700          NaN
...                 ...         ...          ...          ...
2005-12-13   10823.7197   4693.3999    1267.4301  1261.032680
2005-12-14   10883.5098   4674.8501    1272.7400  1261.800013
2005-12-15   10881.6699   4673.1401    1270.9399  1262.155340
2005-12-16   10875.5898   4704.4102    1267.3199  1262.093333
2005-12-19   10836.5303   4694.8599    1259.9200  1262.257333

[1500 rows x 4 columns]

In [ ]:
# Conditional by dates
assets.loc["2010-01-01":"2015-01-01"]

Close DJI30 Close CAC40  Close SP500       SMA 15
time                                                         
2010-01-04   10583.9600   4013.9700    1132.9900  1116.254013
2010-01-05   10572.0195   4012.9099    1136.5200  1118.261347
2010-01-06   10573.6797   4017.6699    1137.1400  1119.796680
2010-01-07   10606.8604   4024.8000    1141.6899  1122.047333
2010-01-08   10618.1904   4045.1399    1144.9800  1124.433993
...                 ...         ...          ...          ...
2014-12-23   18024.1699   4314.9702    2082.1699  2044.893340
2014-12-24   18030.2109   4295.8501    2081.8799  2045.396660
2014-12-29   18038.2305   4317.9302    2090.5701  2046.640007
2014-12-30   17983.0703   4245.5400    2080.3501  2046.972007
2014-12-31   17823.0703   4272.7500    2058.8999  2046.877993

[1245 rows x 4 columns]

In [ ]:
# Conditional by values
assets.loc[assets["Close DJI30"] > 15000]

Close DJI30 Close CAC40  Close SP500       SMA 15
time                                                         
2013-05-07   15056.2002   3921.3201    1625.9600  1583.837320
2013-05-08   15105.1201   3956.2800    1632.6899  1587.711987
2013-05-09   15082.6201   3928.5801    1626.6700  1592.689320
2013-05-10   15118.4902   3953.8301    1633.7000  1598.828653
2013-05-13   15091.6797   3945.2000    1633.7700  1604.063320
...                 ...         ...          ...          ...
2020-03-12   21200.6191   4044.2600    2420.8827  2445.100287
2020-03-13   23185.6191   4118.3599    2418.0191  2444.029520
2020-03-16   20188.5195   3881.4600    2426.6181  2443.003900
2020-03-17   21237.3809   3991.7800    2436.5000  2442.964567
2020-03-18   19898.9199   3754.8401    2398.1001  2440.551540

[1687 rows x 4 columns]

In [ ]:
# Concat some dataframes
df1 = assets.iloc[1500:, :]
df2 = assets.iloc[:1500, :]

pd.concat((df1, df2), axis = 0)

Close DJI30 Close CAC40  Close SP500       SMA 15
time                                                         
2005-12-20   10805.5498   4703.4800    1259.6200  1262.400000
2005-12-21   10833.7305   4752.4102    1262.7900  1263.287333
2005-12-22   10889.4404   4751.9600    1268.1200  1263.517333
2005-12-23   10883.2695   4757.7402    1268.6600  1263.756000
2005-12-27   10777.7695   4769.3799    1256.5400  1263.386000
...                 ...         ...          ...          ...
2005-12-13   10823.7197   4693.3999    1267.4301  1261.032680
2005-12-14   10883.5098   4674.8501    1272.7400  1261.800013
2005-12-15   10881.6699   4673.1401    1270.9399  1262.155340
2005-12-16   10875.5898   4704.4102    1267.3199  1262.093333
2005-12-19   10836.5303   4694.8599    1259.9200  1262.257333

[5047 rows x 4 columns]

# Matplotlib